live_config_reload = true

[terminal]
osc52 = "CopyPaste"

[window]
dimensions = { columns = 100, lines = 30 }
padding = { x = 4, y = 2 }
opacity = 0.95
dynamic_title = true
dynamic_padding = true
decorations = "full"

[font]
normal = { family = "Ubuntu Mono", style = "Medium" }
bold = { family = "Ubuntu Mono", style = "Bold" }
italic = { family = "Ubuntu Mono", style = "italic" }
size = 14.0

[colors]
cursor = { cursor = "#00D1FF" }
primary = { background = "#2c2c34", foreground = "#f5f5f5" }
selection = { background = "#808080", text = "CellForeground" }

[colors.normal]
black = "#110f18"
blue = "#5e5bff"
cyan = "#51f0c5"
green = "#51f085"
magenta = "#e07bff"
red = "#ff5757"
white = "#f0f0f0"
yellow = "#ffd56a"

[colors.bright]
black = "#2d2d2d"
blue = "#8a8aff"
